### ISSUE TITLE
about demo_dan.py

### ISSUE THREAD

**Issue by Susia00** [LeeRel1991/faceAlignment_tensorflow#1]
你好，请问可以将检测后的112*112的人脸输入demo_dan.py吗？输出的landmark不对齐。initLandmarks.npy怎么生成的呢？

**Comment by LeeRel1991** [comment]
可以将人脸检测算法检测到的人脸 输入到demo_dan.py. 最新提交的data/imgs里的人脸图像就是我用sfd检测算法检测到的人脸图像，只是输入给dan前需要crop, 包括： 对检测框进行适当的扩大（以检测框中心，向四周扩充1.2-1.6倍,根据检测结果可微调），resize成112x112,然后灰度化和规范化(这里是减均值除以标准差)。详细的crop代码可参见[ImageCropper](https://github.com/LeeRel1991/faceAlignment_tensorflow/blob/master/face_alignment/utils/data_cropper.py).
initLandmarks.npy记录了平均人脸形状，由训练集样本的ground truth landmarks的平均得到的（我用的训练集是300W中的afw，lfpw，helen）。最新提交已上传，您也可以在自己的数据集上生成。

**Comment by LeeRel1991** [comment]
issue is solved

**Comment by Susia00** [comment]
还有个疑问是，用data_augment处理后的图片来训练，如处理afw并设置大小为112(256、512等)，都会报错“ssize.empty() in function 'resize'”，而用原训练集来训练就没问题，不知道这个报错该如何解决。另外，data_augment处理后的图片很多都是倒立的图片（虽可以设置角度），这种倒立的关键点图片是否有需要拿来训练呢?
具体报错如下：
2018-12-27 19:20:31.413676: W tensorflow/core/framework/op_kernel.cc:1306] Unknown: error: OpenCV(3.4.3) /io/opencv/modules/imgproc/src/resize.cpp:4044: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

Traceback (most recent call last):

  File "/usr/local/public/anaconda2/envs/tf1.4_py35/lib/python3.5/site-packages/tensorflow/python/ops/script_ops.py", line 158, in __call__
    ret = func(*args)

  File "../utils/data_loader.py", line 130, in load_sample_lable
    img, kpt = self.preprocess(img, kpt)

  File "../utils/data_cropper.py", line 105, in __call__
    face_img = cv2.resize(face_img, self.out_size)

cv2.error: OpenCV(3.4.3) /io/opencv/modules/imgproc/src/resize.cpp:4044: error: (-215:Assertion failed) !ssize.empty() in function 'resize'



Traceback (most recent call last):
  File "/usr/local/public/anaconda2/envs/tf1.4_py35/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/usr/local/public/anaconda2/envs/tf1.4_py35/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/public/anaconda2/envs/tf1.4_py35/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: error: OpenCV(3.4.3) /io/opencv/modules/imgproc/src/resize.cpp:4044: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

Traceback (most recent call last):

  File "/usr/local/public/anaconda2/envs/tf1.4_py35/lib/python3.5/site-packages/tensorflow/python/ops/script_ops.py", line 158, in __call__
    ret = func(*args)

  File "../utils/data_loader.py", line 130, in load_sample_lable
    img, kpt = self.preprocess(img, kpt)

  File "../utils/data_cropper.py", line 105, in __call__
    face_img = cv2.resize(face_img, self.out_size)

cv2.error: OpenCV(3.4.3) /io/opencv/modules/imgproc/src/resize.cpp:4044: error: (-215:Assertion failed) !ssize.empty() in function 'resize'



	 [[Node: PyFunc = PyFunc[Tin=[DT_STRING, DT_STRING], Tout=[DT_FLOAT, DT_FLOAT], token="pyfunc_0"](arg0, arg1)]]
	 [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[<unknown>, <unknown>], output_types=[DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../DAN-4-LeeRel/faceAlignment_tensorflow-master/face_alignment/tools/train_dan.py", line 187, in <module>
    train(net, "", train_data, None, out_path)
  File "../DAN-4-LeeRel/faceAlignment_tensorflow-master/face_alignment/tools/train_dan.py", line 121, in train
    img_batch, gt_batch = sess.run(next_element)
  File "/usr/local/public/anaconda2/envs/tf1.4_py35/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/usr/local/public/anaconda2/envs/tf1.4_py35/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/public/anaconda2/envs/tf1.4_py35/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/usr/local/public/anaconda2/envs/tf1.4_py35/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: error: OpenCV(3.4.3) /io/opencv/modules/imgproc/src/resize.cpp:4044: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

Traceback (most recent call last):

  File "/usr/local/public/anaconda2/envs/tf1.4_py35/lib/python3.5/site-packages/tensorflow/python/ops/script_ops.py", line 158, in __call__
    ret = func(*args)

  File "../utils/data_loader.py", line 130, in load_sample_lable
    img, kpt = self.preprocess(img, kpt)

  File "../utils/data_cropper.py", line 105, in __call__
    face_img = cv2.resize(face_img, self.out_size)

cv2.error: OpenCV(3.4.3) /io/opencv/modules/imgproc/src/resize.cpp:4044: error: (-215:Assertion failed) !ssize.empty() in function 'resize'



	 [[Node: PyFunc = PyFunc[Tin=[DT_STRING, DT_STRING], Tout=[DT_FLOAT, DT_FLOAT], token="pyfunc_0"](arg0, arg1)]]
	 [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[<unknown>, <unknown>], output_types=[DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]]
